package:
  name: dlib
  version: "18.11"

source:
  fn: dlib-18.11.tar.bz2
  url: http://sourceforge.net/projects/dclib/files/dlib/v18.11/dlib-18.11.tar.bz2/download
  sha1: 628eeaad8b0640150898ea0e82a53236bac93aed
  
  patches:
   - gui_patch.patch

build:
  number: 0

requirements:
  build:
   - python
   - cmake  # [win]
   - boost 1.56.0
   - jpeg 8d
   - libpng 1.5.13
   - sqlite 3.8.4.1  # [unix]

  run:
   - python
   - boost 1.56.0
   - jpeg 8d
   - libpng 1.5.13
   - sqlite 3.8.4.1  # [unix]

test:
  imports:
    - dlib

about:
  home: http://dlib.net/
  license: Boost Software License
