package:
  name: dlib
  version: "18.15"

source:
  fn: dlib-18.15.tar.bz2
  url: http://sourceforge.net/projects/dclib/files/dlib/v18.15/dlib-18.15.tar.bz2/download
  sha1: d2b5f25116d62290f85e41b6cbebb0b1e7acffb2

build:
  number: 0

requirements:
  build:
   - python
   - cmake  # [win]
   - boost 1.56.0
   - sqlite 3.8.4.1  # [unix]

  run:
   - python
   - boost 1.56.0
   - sqlite 3.8.4.1  # [unix]

test:
  imports:
    - dlib

about:
  home: http://dlib.net/
  license: Boost Software License
