package:
  name: dlib
  version: "18.18"

source:
  fn: dlib-18.18.tar.bz2
  url: http://sourceforge.net/projects/dclib/files/dlib/v18.18/dlib-18.18.tar.bz2/download
  sha1: 21421b55e22387dfa428a221653172bf740b55ed

  patches:
    - cmake_static_boost.patch  # [win]

build:
  number: 2

requirements:
  build:
   - python
   - cmake
   - numpy >=1.10
   - boost 1.59.*
   # On OSX Davis has forced building the static version
   # On Windows there is a conflict between this jpeg and windows.h
   - jpeg            # [linux]
   - libpng 1.6.*
   - sqlite 3.*      # [unix]

  run:
   - python
   - numpy >=1.10
   - boost 1.59.*
   - jpeg            # [linux]
   - libpng 1.6.*
   - sqlite 3.*      # [unix]

test:
  requires:
    - pillow

  imports:
    - dlib

about:
  home: http://dlib.net/
  license: Boost Software License
